### ISSUE TITLE
Add an option to delete the shared files

### ISSUE THREAD

**Issue by CodeCubeNeo** [roozbehzarei/filester#12]
I think it would be nice to have an option to delete the shared files, when you don't need them anymore (or at least add an option to share the file for less than 14 days).

**Comment by rouzbehzarei** [comment]
> I think it would be nice to have an option to delete the shared files, when you don't need them anymore (or at least add an option to share the file for less than 14 days).

Unfortunately the server doesn't provide an option to set a custom expire date (less than 14 days) but I will definitely add the option to delete files in the next release.

**Comment by CodeCubeNeo** [comment]
Awesome

**Comment by CodeCubeNeo** [comment]
Any progress on this?

**Comment by roozbehzarei** [comment]
> Any progress on this?

This feature will definitely be added in next release and it won't take as much time as this update took.

**Comment by WeberAlex** [comment]
Could we also have a clear or delete option for overdue files (maybe sliding the file on the left or right)? I see my expired files in Filester with 0 MB. I want to see the current files only.

**Comment by roozbehzarei** [comment]
> Could we also have a clear or delete option for overdue files (maybe sliding the file on the left or right)? I see my expired files in Filester with 0 MB. I want to see the current files only.

I'll implement this feature in the upcoming update. Giving you the option to choose from deleting files only from history or from the internet also.
