### ISSUE TITLE
Fails to upload any files

### ISSUE THREAD

**Issue by Randeu** [roozbehzarei/filester#16]
The app was working fine for 2-3 days but suddenly it fails to upload any files. I have tried uploading files of different format but always get error saying failed to upload.

**Comment by roozbehzarei** [comment]
> The app was working fine for 2-3 days but suddenly it fails to upload any files. I have tried uploading files of different format but always get error saying failed to upload.

I just tested the app and it's working fine. Are you sure your connection is stable? You can try uploading to transfer.sh directly using the [website](https://transfer.sh/) to confirm network connectivity.
