### ISSUE TITLE
Cannot cancel a file transfer

### ISSUE THREAD

**Issue by serrq** [roozbehzarei/filester#22]
I cannot cancel a previously started file uploading.

![Screenshot_2022-09-30-13-22-42-91_b52257a2dc2f0362f8c2187ecbe4cebf (1)](https://user-images.githubusercontent.com/113377431/193259741-2f2a59a8-6c81-4d55-bfe2-f2ee3cda0ea7.jpg)

**Comment by roozbehzarei** [comment]
This feature is now added to the roadmap for next release. You can track its progress [here](https://github.com/roozbehzarei/filester/projects/3#card-85962823).

**Comment by roozbehzarei** [comment]
> Please add the latest version on Fdroid too. Many thanks.

F-Droid app submission happens automatically (pulled from GitHub releases) but often has a delay of one week.
