### ISSUE TITLE
Troubles with files uploading...

### ISSUE THREAD

**Issue by serrq** [roozbehzarei/filester#25]
For the past couple of hours all uploads fail during upload. It is not clear why.

![Screenshot_2022-09-30-13-40-21-43_b783bf344239542886fee7b48fa4b892 (1)](https://user-images.githubusercontent.com/113377431/193262214-17129fd5-79e5-4200-93de-3385f99bbfcf.jpg)

**Comment by roozbehzarei** [comment]
Filester relies on transfer.sh servers as for the storage of uploaded files. Your uploads might keep failing during downtime of their servers. There's nothing that we could do to help it.
