### ISSUE TITLE
[Request] Adding more uploading platforms

### ISSUE THREAD

**Issue by serrq** [roozbehzarei/filester#26]
In addition to transfer.sh I'd like to using also these two platforms (if possible): 

https://webwormhole.io/ 

https://wormhole.app/

I am unable to tell if they are free (foss) platforms because I am not a computer technician.

**Comment by roozbehzarei** [comment]
https://webwormhole.io/ is intended for letting computers join each other (P2P) and doesn't relate to sharing files on the internet.

As for the https://wormhole.app/ , unfortunately the platform is not open-source (thus not secure, although claimed to be) and stores files for 24 hours only).

**Comment by roozbehzarei** [comment]
FYI, according to the FAQ section on wormhole.app:

**Is this an open source project?**
The source code for the streaming encryption implementation, based on Encrypted Content-Encoding for HTTP (RFC 8188) is [open source](https://github.com/SocketDev/wormhole-crypto). The full client and server code may be open sourced in the future.

They also have a roadmap which indicates there's already an Android app in development for the platform.
