### ISSUE TITLE
[question] Meaning of : 'Please enter the deletion token'

### ISSUE THREAD

**Issue by gbdomubpkm** [roozbehzarei/filester#32]
Hello !

Thank you for this useful app that I discovered this evening, hence a question that may seem silly because I am experimenting and i don't know anything about the app..

I uploaded a basic file:
https:transfer.sh890gbxUp90aireplane.jpg

To delete the file, it is marked: 'please enter the deletion token' . What is it about ?

Can the uploader delete an uploaded file as suggested?

Maybe a basic user manual or a page of what we can do / we can't do / how to do / with the app would be useful.

Best regards

**Comment by roozbehzarei** [comment]
> Hello !
> 
> Thank you for this useful app that I discovered this evening, hence a question that may seem silly because I am experimenting and i don't know anything about the app..
> 
> I uploaded a basic file: https:transfer.sh890gbxUp90aireplane.jpg
> 
> To delete the file, it is marked: 'please enter the deletion token' . What is it about ?
> 
> Can the uploader delete an uploaded file as suggested?
> 
> Maybe a basic user manual or a page of what we can do / we can't do / how to do / with the app would be useful.
> 
> Best regards

Thank you for using Filester! This app uses transfer.sh cloud to store its files which gives you a deletion token upon uploading a file. In the next release I will implement the feature to store deletion tokens locally, therefore giving the user the option to delete uploaded files whenever they want.

**Comment by gbdomubpkm** [comment]
Thank you very much for the quick response.
