### ISSUE TITLE
Make the donation process easier (to support development)

### ISSUE THREAD

**Issue by serrq** [roozbehzarei/filester#37]
Please add direct cryptocurrency addresses within the app. Easy tap and donate without leaving the app: I don't want going around to websites. I don't want support FIAT economy.

TRX, AVAX, LTC, BTC, XEC, BNB, SOL, BCH, ALGO, XTZ, XDC, DASH, FTM, XRP, ADA, XMR addresses available for donations (addresses have to be copyable).

Here an example from other developers.

![1000092943](https://github.com/roozbehzarei/filester/assets/113377431/ad34a018-66ae-4443-9d0c-484d17323161)

**Comment by roozbehzarei** [comment]
Of course! Would you please provide the name of an application that has done this the way you provided? I need to manually review the process to understand how they've achieved it.

**Comment by roozbehzarei** [comment]
Currently, the app points users to my website where they can see multiple crypto addresses and can copy them by tapping on one of the addresses. The "sponsor" button on GitHub however, was broken which is fixed now.

**Comment by roozbehzarei** [comment]
> Please share this method with other developers 🙏 ❤️ once you understood how to implement it (in the true foss spirit). I am not a developer.

Who knows? Maybe I'll publish a guide for it 👀

**Comment by roozbehzarei** [comment]
> No longer go around websites (outside the app). See the new way: everything happens within the app (even offline).
> 
> Unstoppable Wallet https://github.com/horizontalsystems/unstoppable-wallet-android
> 
> TimePlanner https://github.com/v1tzor/TimePlanner

I took a look at the TimePlannet app. Their implementation is not standard because they have hardcoded their wallet addresses. To update them (if necessary), they have to publish an update which could lead to several problems.
Therefore I'm closing this issue.

**Comment by roozbehzarei** [comment]
> To have the crypto addresses available even offline they have to stay stored in the code. Mandatory. There is no alternative.
> 
> TimePlanner developer has already changed a crypto address through an update. We have adjusted to the new address. What should happen of complicated? In any case it is your choice.

There is a scenario, in which the developer loses access to one address. In this case, they push an update with the new address. If the user doesn't update their app, they might make a transaction to the old one, therefore wasting the fund.
From the technical POV, dynamic content such as Privacy Policy, Terms of Service and Donation sections should always be called from the internet, so that users still using older releases be able to see latest changes in those sections.
