### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [roozbehzarei/filester#40]
...as Firebase is not-FOSS and it gets cleaned

ref: https://monitor.f-droid.org/builds/log/com.roozbehzarei.filester/6#site-footer

**Comment by roozbehzarei** [comment]
Thank you for notifying me of this situation. I see the issue is FCM, as I've been using other Firebase modules in the past releases with no issues. I release a hotfix removing FCM.
Can you confirm if Firestore would be problematic as well?

**Comment by linsui** [comment]
We removed all firebase libs with `sed -i -e '/gms/d' -e '/firebase/d' {..,.}/build.gradle.kts`. And for the latest version this causes build failure. Which lib is the firestore?

**Comment by roozbehzarei** [comment]
It's another Firebase library which is a database solution for backend services. Of course it has open-source alternatives like Supabase.

**Comment by licaon-kter** [comment]
source code link to that Firestore? I only see "Google", and that's not good news :) :)

**Comment by roozbehzarei** [comment]
I understand the concern. I have released a [new version](https://github.com/roozbehzarei/filester/releases/tag/v2.3.1) with all Google services removed and replaced Firebase with FOSS alternatives.
