### ISSUE TITLE
Can't upload files

### ISSUE THREAD

**Issue by akrram0** [roozbehzarei/filester#45]
The app doesn't seem to work when I try to send a screenshot to test the app I got this
![Screenshot_2024-04-01-23-29-33-00_b52257a2dc2f0362f8c2187ecbe4cebf](https://github.com/roozbehzarei/filester/assets/140515513/c3bdcc8f-8bbf-42b3-b064-4b1188823c74)

**Comment by roozbehzarei** [comment]
There's a button on top right corner of Filester that lets you check if the server is online or down. Unfortunately the server has been down in the last several weeks. I will soon change the server and release an update to fix this problem.

**Comment by roozbehzarei** [comment]
Fixed in #46
