### ISSUE TITLE
Options Menu navigation not working properly

### ISSUE THREAD

**Issue by roozbehzarei** [roozbehzarei/filester#9]
Clicking on an Options Menu item repeatedly prevents back navigation button to work. For example if an item is clicked 4 times in the menu, the user needs to click on back button 4 times in order for navigation to function.

**Comment by jstetten** [comment]
Sorry, where is the options menu? My v1.0 Android app has two panes and a small info ℹ page.

Customization of some options would indeed be very welcome.

**Comment by roozbehzarei** [comment]
> Sorry, where is the options menu? My v1.0 Android app has two panes and a small info ℹ page.
> 
> Customization of some options would indeed be very welcome.

That small ℹ icon is the only item of the option's menu which is set to be always visible (hence there's no drop-down menu)
